{% set version = "26.2.5" %}

package:
  name: erlang
  version: {{ version }}

source:
  url: https://github.com/erlang/otp/archive/OTP-{{ version }}.tar.gz
  sha256: d34b409cb5968ae47dd5a0c4f85b925d5601898d90788bbb08d514964a3a141d

build:
  number: 2
  skip: true  # [win]

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - gnuconfig
    - make
  host:
    - perl
    - readline
    - openssl
    - ncurses
    - zlib
  run:
    - readline
    - openssl
    - ncurses
    - zlib

test:
  commands:
    - which erl
    - which erlc
    - erl -version    # [build_platform == target_platform]
    - erlc            # [build_platform == target_platform]

about:
  home: https://www.erlang.org/
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: A programming language used to build massively scalable soft real-time systems with requirements on high availability.
  dev_url: https://github.com/erlang/otp

extra:
  recipe-maintainers:
    - anthchirp
    - scopatz
    - jakirkham
    - sodre
    - danielhollas
