{% set version = "24.1.3" %}

package:
  name: erlang
  version: {{ version }}

source:
  url: https://github.com/erlang/otp/archive/OTP-{{ version }}.tar.gz
  sha256: 7ccfa8372995fc7895baeb3729f679aff87781d1b7c734acd22740bc41ee2eed

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - autoconf 2.*
    - m4 1.4.*
  host:
    - perl
    - readline
    - openssl
    - ncurses
    - zlib
  run:
    - readline
    - openssl
    - ncurses
    - zlib

test:
  commands:
    - erl -version
    - erlc

about:
  home: https://www.erlang.org/
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: A programming language used to build massively scalable soft real-time systems with requirements on high availability.
  dev_url: https://github.com/erlang/otp

extra:
  recipe-maintainers:
    - anthchirp
    - scopatz
    - jakirkham
    - sodre
