{% set version = "28.0.1" %}

package:
  name: erlang
  version: {{ version }}

source:
  url: https://github.com/erlang/otp/archive/OTP-{{ version }}.tar.gz
  sha256: a5c66958a0b9382f65345638c2cc146239721237db842bb8856a4792800dfd46

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - gnuconfig
    - make
    - zlib  # [build_platform != target_platform]
  host:
    - perl
    - readline
    - openssl
    - ncurses
    - zlib
  run:
    - readline
    - openssl
    - ncurses
    - zlib

test:
  commands:
    - which erl
    - which erlc
    - erl -version    # [build_platform == target_platform]
    - erlc            # [build_platform == target_platform]

about:
  home: https://www.erlang.org/
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: A programming language used to build massively scalable soft real-time systems with requirements on high availability.
  dev_url: https://github.com/erlang/otp

extra:
  recipe-maintainers:
    - anthchirp
    - scopatz
    - jakirkham
    - sodre
    - danielhollas
