{% set version = "26.2.3" %}

package:
  name: erlang
  version: {{ version }}

source:
  url: https://github.com/erlang/otp/archive/OTP-{{ version }}.tar.gz
  sha256: 7a79e7955890b06572dbb3c3460771a71f729c15bc6ced018916a432669fd239

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - autoconf 2.*
    - m4 1.4.*
    - make
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - perl
    - readline
    - openssl
    - ncurses
    - zlib
  run:
    - readline
    - openssl
    - ncurses
    - zlib

test:
  commands:
    - erl -version
    - erlc

about:
  home: https://www.erlang.org/
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: A programming language used to build massively scalable soft real-time systems with requirements on high availability.
  dev_url: https://github.com/erlang/otp

extra:
  recipe-maintainers:
    - anthchirp
    - scopatz
    - jakirkham
    - sodre
