{% set version = "27.2.4" %}

package:
  name: erlang
  version: {{ version }}

source:
  url: https://github.com/erlang/otp/archive/OTP-{{ version }}.tar.gz
  sha256: 0504fd9978e7b002d760c1a4a7268832e8842f2c10fe25e570c6c2d0a64be63c

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - gnuconfig
    - make
    - zlib  # [build_platform != target_platform]
  host:
    - perl
    - readline
    - openssl
    - ncurses
    - zlib
  run:
    - readline
    - openssl
    - ncurses
    - zlib

test:
  commands:
    - which erl
    - which erlc
    - erl -version    # [build_platform == target_platform]
    - erlc            # [build_platform == target_platform]

about:
  home: https://www.erlang.org/
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: A programming language used to build massively scalable soft real-time systems with requirements on high availability.
  dev_url: https://github.com/erlang/otp

extra:
  recipe-maintainers:
    - anthchirp
    - scopatz
    - jakirkham
    - sodre
    - danielhollas
